In [125]:
import numpy as np
from pandas import read_csv
from numpy import array
from numpy import reshape

In [126]:
data = [11,22,33,44,55]

In [127]:
type(data)


list

In [128]:
# array is a collection of similar data elements stored at contiguous memory locations.


In [129]:
np.array(data)

array([11, 22, 33, 44, 55])

In [130]:
type (data)

list

In [131]:
data = np.array(data)

In [132]:
type(data)

numpy.ndarray

In [133]:
print(data)

[11 22 33 44 55]


In [134]:
# one dimension array - list of an array of value ( not colum not row) is a collection of things

#  two dimentions would have colum and rowms

In [135]:
data2D = [[11,22], [33,34], [55,56]]

In [136]:
print(data2D)

[[11, 22], [33, 34], [55, 56]]


In [137]:
type(data2D)

list

In [138]:
data2D = np.array(data2D)


In [139]:
print(data2D)

[[11 22]
 [33 34]
 [55 56]]


In [140]:
data

array([11, 22, 33, 44, 55])

In [141]:
len(data)

5

In [142]:
data[0]
# showns the first number

11

In [143]:
data[4]
# showns the last number
# we also can use [-1] to find the last number.

55

In [144]:
data[0:3]

array([11, 22, 33])

In [145]:
dataB = np.array([11,22,33,44,55,66,77,88,99])

In [146]:
dataB[1:5]

array([22, 33, 44, 55])

In [147]:
dataB[1:]

array([22, 33, 44, 55, 66, 77, 88, 99])

In [148]:
dataB[ :5]


array([11, 22, 33, 44, 55])

In [149]:
data2D[0,1]

22

In [150]:
data2D[ : ,1]

array([22, 34, 56])

In [151]:
# COLLUNS ARE AFTER THE COMMA
data2D[ : , 0]

array([11, 33, 55])

In [152]:
data2D[ : , : -1]

array([[11],
       [33],
       [55]])

In [153]:
X,y=data2D[:,:-1], data2D[:,-1]

In [154]:
y

array([22, 34, 56])

In [155]:
X

array([[11],
       [33],
       [55]])

In [156]:
data

array([11, 22, 33, 44, 55])

In [157]:
data.shape


(5,)

In [158]:
data = data.reshape((data.shape[0],1))

In [159]:
print(data)

[[11]
 [22]
 [33]
 [44]
 [55]]


In [162]:
data3D=data2D.reshape((data2D.shape[0], 
                       data2D.shape[1],1))

In [163]:
data3D.shape

(3, 2, 1)